广播机制

pytorch中的广播机制和numpy中的广播机制一样, 因为都是数组的广播机制

1)程序会自动执行操作使得A.shape==B.shape, 

2)对应位置进行相加
运算结果的shape是:A.shape和B.shape对应位置的最大值,比如:A.shape=(1,9,4),B.shape=(15,1,4),那么A+B的shape是(15,9,4)

有两种情况能够进行广播

A.ndim > B.ndim, 并且A.shape最后几个元素包含B.shape, 比如下面三种情况, 注意不要混淆ndim和shape这两个基本概念
A.shape=(2,3,4,5), B.shape=(3,4,5)
A.shape=(2,3,4,5), B.shape=(4,5)
A.shape=(2,3,4,5), B.shape=(5)

A.ndim == B.ndim, 并且A.shape和B.shape对应位置的元素要么相同要么其中一个是1, 比如
A.shape=(1,9,4), B.shape=(15,1,4)
A.shape=(1,9,4), B.shape=(15,1,1)


In [6]:
import torch
B=torch.zeros(3)
print(B,B.shape)
W=torch.normal(0,1,(2,3))
X=torch.normal(0,1,(4,2))
print(torch.matmul(X,W)+B)


tensor([0., 0., 0.]) torch.Size([3])
tensor([[-0.3940, -0.6602, -0.5950],
        [ 0.6206,  0.0314,  0.1381],
        [ 0.9089,  2.6206,  2.2426],
        [-0.4694, -0.3231, -0.3416]])


In [8]:
import numpy as np
# a.shape=(2,2,3,4)
a = np.arange(1,49).reshape((2,2,3,4))
# b.shape=(3,4)
b = np.arange(1,13).reshape((3,4))
# numpy会将b.shape调整至(2,2,3,4), 这一步相当于numpy自动实现np.tile(b,[2,2,1,1])
res = a + b
print('===================================')
print(a)
print(a.shape)
print('===================================')
print(b)
print(b.shape)
print('===================================')
print(res)
print(res.shape)
print('===================================')
print(a+b == a + np.tile(b,[2,2,1,1]) )


[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]


 [[[25 26 27 28]
   [29 30 31 32]
   [33 34 35 36]]

  [[37 38 39 40]
   [41 42 43 44]
   [45 46 47 48]]]]
(2, 2, 3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[[ 2  4  6  8]
   [10 12 14 16]
   [18 20 22 24]]

  [[14 16 18 20]
   [22 24 26 28]
   [30 32 34 36]]]


 [[[26 28 30 32]
   [34 36 38 40]
   [42 44 46 48]]

  [[38 40 42 44]
   [46 48 50 52]
   [54 56 58 60]]]]
(2, 2, 3, 4)
[[[[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]]


 [[[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]

  [[ True  True  True  True]
   [ True  True  True  True]
   [ True  True  True  True]]]]
