In [1]:
import torch
from torch import nn

net=nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
X=torch.ones((2,4))
net(X)

tensor([[0.1159],
        [0.1159]], grad_fn=<AddmmBackward>)

In [5]:
print(net[0].state_dict(),
net[0].weight,
type(net[0].weight.data),
net[0].weight.grad,)

OrderedDict([('weight', tensor([[-0.0958, -0.1669,  0.1738, -0.1238],
        [ 0.1542, -0.3612, -0.1939, -0.2898],
        [-0.3141, -0.4290, -0.4160,  0.4810],
        [ 0.2281,  0.1871,  0.0518, -0.4493],
        [-0.3660,  0.1604,  0.1202,  0.1849],
        [-0.1522, -0.3925, -0.0733,  0.0139],
        [ 0.1780,  0.1424,  0.3374, -0.4434],
        [ 0.1976,  0.4818,  0.0729, -0.2860]])), ('bias', tensor([-0.2941,  0.3805, -0.1116, -0.2840,  0.1466, -0.3177,  0.4697,  0.0669]))]) Parameter containing:
tensor([[-0.0958, -0.1669,  0.1738, -0.1238],
        [ 0.1542, -0.3612, -0.1939, -0.2898],
        [-0.3141, -0.4290, -0.4160,  0.4810],
        [ 0.2281,  0.1871,  0.0518, -0.4493],
        [-0.3660,  0.1604,  0.1202,  0.1849],
        [-0.1522, -0.3925, -0.0733,  0.0139],
        [ 0.1780,  0.1424,  0.3374, -0.4434],
        [ 0.1976,  0.4818,  0.0729, -0.2860]], requires_grad=True) <class 'torch.Tensor'> None


In [14]:
print([(name,para) for name,para in net[0].named_parameters()])
print(*[(name,para) for name,para in net[0].named_parameters()])
print(type(net[0].named_parameters()))
print(X,*X)
X=torch.zeros((2,2,2))
print(*X)

[('weight', Parameter containing:
tensor([[-0.0958, -0.1669,  0.1738, -0.1238],
        [ 0.1542, -0.3612, -0.1939, -0.2898],
        [-0.3141, -0.4290, -0.4160,  0.4810],
        [ 0.2281,  0.1871,  0.0518, -0.4493],
        [-0.3660,  0.1604,  0.1202,  0.1849],
        [-0.1522, -0.3925, -0.0733,  0.0139],
        [ 0.1780,  0.1424,  0.3374, -0.4434],
        [ 0.1976,  0.4818,  0.0729, -0.2860]], requires_grad=True)), ('bias', Parameter containing:
tensor([-0.2941,  0.3805, -0.1116, -0.2840,  0.1466, -0.3177,  0.4697,  0.0669],
       requires_grad=True))]
('weight', Parameter containing:
tensor([[-0.0958, -0.1669,  0.1738, -0.1238],
        [ 0.1542, -0.3612, -0.1939, -0.2898],
        [-0.3141, -0.4290, -0.4160,  0.4810],
        [ 0.2281,  0.1871,  0.0518, -0.4493],
        [-0.3660,  0.1604,  0.1202,  0.1849],
        [-0.1522, -0.3925, -0.0733,  0.0139],
        [ 0.1780,  0.1424,  0.3374, -0.4434],
        [ 0.1976,  0.4818,  0.0729, -0.2860]], requires_grad=True)) ('bias', Pa

In [15]:
net.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.0958, -0.1669,  0.1738, -0.1238],
                      [ 0.1542, -0.3612, -0.1939, -0.2898],
                      [-0.3141, -0.4290, -0.4160,  0.4810],
                      [ 0.2281,  0.1871,  0.0518, -0.4493],
                      [-0.3660,  0.1604,  0.1202,  0.1849],
                      [-0.1522, -0.3925, -0.0733,  0.0139],
                      [ 0.1780,  0.1424,  0.3374, -0.4434],
                      [ 0.1976,  0.4818,  0.0729, -0.2860]])),
             ('0.bias',
              tensor([-0.2941,  0.3805, -0.1116, -0.2840,  0.1466, -0.3177,  0.4697,  0.0669])),
             ('2.weight',
              tensor([[ 0.1723,  0.0330,  0.2481,  0.0194, -0.3062, -0.1629,  0.1157,  0.1754]])),
             ('2.bias', tensor([0.0185]))])

In [21]:
def block1():
  net=nn.Sequential(nn.Linear(2,1),nn.ReLU(),nn.Linear(1,2),nn.ReLU())
  return net
def block2():
  net=nn.Sequential()
  for i in range(2):
    net.add_module(f'block{i}',block1())
  net=nn.Sequential(net,nn.Linear(2,1))
  return net

regnet=block2()
print(regnet)
print(regnet[0][1][0].bias)


Sequential(
  (0): Sequential(
    (block0): Sequential(
      (0): Linear(in_features=2, out_features=1, bias=True)
      (1): ReLU()
      (2): Linear(in_features=1, out_features=2, bias=True)
      (3): ReLU()
    )
    (block1): Sequential(
      (0): Linear(in_features=2, out_features=1, bias=True)
      (1): ReLU()
      (2): Linear(in_features=1, out_features=2, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=2, out_features=1, bias=True)
)
Parameter containing:
tensor([-0.3992], requires_grad=True)


初始化

In [22]:
def init_norm(m):
  if (type(m)==nn.Linear):
    nn.init.normal_(m.weight,0,0.01)
    nn.init.zeros_(m.bias)

net.apply(init_norm)
net[0].weight.data,net[0].bias.data

(tensor([[ 0.0079, -0.0046,  0.0054, -0.0153],
         [-0.0123, -0.0044, -0.0056,  0.0108],
         [-0.0045, -0.0043, -0.0135, -0.0117],
         [ 0.0004,  0.0015, -0.0097, -0.0045],
         [-0.0104, -0.0021,  0.0110, -0.0073],
         [ 0.0163,  0.0030,  0.0055, -0.0137],
         [-0.0235,  0.0145,  0.0058, -0.0112],
         [-0.0019, -0.0050,  0.0055, -0.0116]]),
 tensor([0., 0., 0., 0., 0., 0., 0., 0.]))

In [ ]:
#自定义初始化
def my_init(m):
    if type(m) == nn.Linear:
        print("Init", *[(name, param.shape)
                        for name, param in m.named_parameters()][0])
        nn.init.uniform_(m.weight, -10, 10)
        m.weight.data *= m.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]
#直接赋值
net[0].weight.data[:] += 1
net[0].weight.data[0, 0] = 42
net[0].weight.data[0]


#共享参数
# 我们需要给共享层一个名称，以便可以引用它的参数
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.Linear(8, 1))
net(X)
# 检查参数是否相同
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
# 确保它们实际上是同一个对象，而不只是有相同的值
print(net[2].weight.data[0] == net[4].weight.data[0])

# 保存

In [3]:
import torch
x=torch.arange(4)
torch.save(x,'x-file')
x2=torch.load('x-file')

In [4]:
print(x2)

tensor([0, 1, 2, 3])
